[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
SMOLTCP_DNS_MAX_RESULT_COUNT = "4"
SMOLTCP_DNS_MAX_SERVER_COUNT = "4"
