name: Deploy the application to the Sign

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: thumbv6m-none-eabi
          components: llvm-tools

      - run: cargo build --release
        working-directory: application

      - run: cargo install cargo-binutils
        
      - run: cargo objcopy --release --bin application -- -O binary application.bin

      - run: echo "APP_VERSION=$(cat application/Cargo.toml | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+" | head -n 1)" >> $GITHUB_OUTPUT
        id: version
      
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          make_latest: true
          tag_name: ${{ steps.version.outputs.APP_VERSION }}
          token: ${{ secrets.GH_TOKEN }}
          files: target/thumbv6m-none-eabi/release/application.bin